module.exports = {
  CONTEXT:               "@context",
  GRAPH:                 "@graph",
  ID:                    "id",
  INDEX:                 "@index",
  LANGUAGE:              "@language",
  LIST:                  "@list",
  NEST:                  "@nest",
  NONE:                  "@none",
  PREFIX:                "@prefix",
  REVERSE:               "@reverse",
  SET:                   "@set",
  TYPE:                  "type",
  VALUE:                 "value",
  VERSION:               "@version",
  VOCAB:                 "@vocab",
  FRAME:                 "@frame",
  NAME:                  "@name",
  REMOVE:                "@remove",
  REDACT:                "@redact",
  DEFAULT:               "@default",
  KEY_ORDER:             "@keyOrder",
  ADDITIONAL_PROPERTIES: "@additionalProperties"
}
