env:
  es6: true
  node: true
extends:
  - 'xo/esnext'
  - './node_modules/xo/config/plugins.js'
parserOptions:
  ecmaVersion: 2016
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
