package com.imprev.jsonrpc.generated.customer;

/**
 * DO NOT EDIT THIS FILE!
 *
 * Generated by Barrister Idl2Java:
 * https://github.com/coopernurse/barrister-java
 *
 * Generated at: Tue Jan 08 12:22:51 PST 2019
 */
public class ExternalUser implements com.bitmechanic.barrister.BStruct {

	public static class Builder {
		private String _externalUserId;

		public Builder externalUserId(String externalUserId) {
			this._externalUserId = externalUserId;
			return this;
		}

		private String _source;

		public Builder source(String source) {
			this._source = source;
			return this;
		}

		private com.imprev.jsonrpc.generated.common.NameValue[] _meta;

		public Builder meta(com.imprev.jsonrpc.generated.common.NameValue[] meta) {
			this._meta = meta;
			return this;
		}

		private String[] _metaOrgKeys;

		public Builder metaOrgKeys(String[] metaOrgKeys) {
			this._metaOrgKeys = metaOrgKeys;
			return this;
		}

		private String _orgLabel;

		public Builder orgLabel(String orgLabel) {
			this._orgLabel = orgLabel;
			return this;
		}

		private UserStatus _status;

		public Builder status(UserStatus status) {
			this._status = status;
			return this;
		}

		private String _localLanguage;

		public Builder localLanguage(String localLanguage) {
			this._localLanguage = localLanguage;
			return this;
		}

		private String _localCountry;

		public Builder localCountry(String localCountry) {
			this._localCountry = localCountry;
			return this;
		}

		private String _email;

		public Builder email(String email) {
			this._email = email;
			return this;
		}

		private String _firstName;

		public Builder firstName(String firstName) {
			this._firstName = firstName;
			return this;
		}

		private String _middleInitial;

		public Builder middleInitial(String middleInitial) {
			this._middleInitial = middleInitial;
			return this;
		}

		private String _lastName;

		public Builder lastName(String lastName) {
			this._lastName = lastName;
			return this;
		}

		private String _street1;

		public Builder street1(String street1) {
			this._street1 = street1;
			return this;
		}

		private String _street2;

		public Builder street2(String street2) {
			this._street2 = street2;
			return this;
		}

		private String _city;

		public Builder city(String city) {
			this._city = city;
			return this;
		}

		private String _state;

		public Builder state(String state) {
			this._state = state;
			return this;
		}

		private String _country;

		public Builder country(String country) {
			this._country = country;
			return this;
		}

		private String _postalCode;

		public Builder postalCode(String postalCode) {
			this._postalCode = postalCode;
			return this;
		}

		private String _userImageUrl;

		public Builder userImageUrl(String userImageUrl) {
			this._userImageUrl = userImageUrl;
			return this;
		}

		private String _companyId;

		public Builder companyId(String companyId) {
			this._companyId = companyId;
			return this;
		}

		private String _officeId;

		public Builder officeId(String officeId) {
			this._officeId = officeId;
			return this;
		}

		private String _officeName;

		public Builder officeName(String officeName) {
			this._officeName = officeName;
			return this;
		}

		private String _officeUrl;

		public Builder officeUrl(String officeUrl) {
			this._officeUrl = officeUrl;
			return this;
		}

		private String _officeEmail;

		public Builder officeEmail(String officeEmail) {
			this._officeEmail = officeEmail;
			return this;
		}

		private String _agentProfilePage;

		public Builder agentProfilePage(String agentProfilePage) {
			this._agentProfilePage = agentProfilePage;
			return this;
		}

		private String _phone1;

		public Builder phone1(String phone1) {
			this._phone1 = phone1;
			return this;
		}

		private String _phone1Type;

		public Builder phone1Type(String phone1Type) {
			this._phone1Type = phone1Type;
			return this;
		}

		private String _phone2;

		public Builder phone2(String phone2) {
			this._phone2 = phone2;
			return this;
		}

		private String _phone2Type;

		public Builder phone2Type(String phone2Type) {
			this._phone2Type = phone2Type;
			return this;
		}

		private String _phone3;

		public Builder phone3(String phone3) {
			this._phone3 = phone3;
			return this;
		}

		private String _phone3Type;

		public Builder phone3Type(String phone3Type) {
			this._phone3Type = phone3Type;
			return this;
		}

		private String _timeZoneId;

		public Builder timeZoneId(String timeZoneId) {
			this._timeZoneId = timeZoneId;
			return this;
		}

		private String _title;

		public Builder title(String title) {
			this._title = title;
			return this;
		}

		private String _license;

		public Builder license(String license) {
			this._license = license;
			return this;
		}

		private String _designation;

		public Builder designation(String designation) {
			this._designation = designation;
			return this;
		}

		private String _facebookUrl;

		public Builder facebookUrl(String facebookUrl) {
			this._facebookUrl = facebookUrl;
			return this;
		}

		private String _twitterUrl;

		public Builder twitterUrl(String twitterUrl) {
			this._twitterUrl = twitterUrl;
			return this;
		}

		private String _linkedInUrl;

		public Builder linkedInUrl(String linkedInUrl) {
			this._linkedInUrl = linkedInUrl;
			return this;
		}

		public ExternalUser build() {
			return new ExternalUser(this._externalUserId, this._source, this._meta, this._metaOrgKeys, this._orgLabel,
					this._status, this._localLanguage, this._localCountry, this._email, this._firstName, this._middleInitial,
					this._lastName, this._street1, this._street2, this._city, this._state, this._country, this._postalCode,
					this._userImageUrl, this._companyId, this._officeId, this._officeName, this._officeUrl, this._officeEmail,
					this._agentProfilePage, this._phone1, this._phone1Type, this._phone2, this._phone2Type, this._phone3,
					this._phone3Type, this._timeZoneId, this._title, this._license, this._designation, this._facebookUrl,
					this._twitterUrl, this._linkedInUrl);
		}

		public Builder() {
		}

		public Builder(ExternalUser obj) {
			this._externalUserId = obj.getExternalUserId();
			this._source = obj.getSource();
			this._meta = obj.getMeta();
			this._metaOrgKeys = obj.getMetaOrgKeys();
			this._orgLabel = obj.getOrgLabel();
			this._status = obj.getStatus();
			this._localLanguage = obj.getLocalLanguage();
			this._localCountry = obj.getLocalCountry();
			this._email = obj.getEmail();
			this._firstName = obj.getFirstName();
			this._middleInitial = obj.getMiddleInitial();
			this._lastName = obj.getLastName();
			this._street1 = obj.getStreet1();
			this._street2 = obj.getStreet2();
			this._city = obj.getCity();
			this._state = obj.getState();
			this._country = obj.getCountry();
			this._postalCode = obj.getPostalCode();
			this._userImageUrl = obj.getUserImageUrl();
			this._companyId = obj.getCompanyId();
			this._officeId = obj.getOfficeId();
			this._officeName = obj.getOfficeName();
			this._officeUrl = obj.getOfficeUrl();
			this._officeEmail = obj.getOfficeEmail();
			this._agentProfilePage = obj.getAgentProfilePage();
			this._phone1 = obj.getPhone1();
			this._phone1Type = obj.getPhone1Type();
			this._phone2 = obj.getPhone2();
			this._phone2Type = obj.getPhone2Type();
			this._phone3 = obj.getPhone3();
			this._phone3Type = obj.getPhone3Type();
			this._timeZoneId = obj.getTimeZoneId();
			this._title = obj.getTitle();
			this._license = obj.getLicense();
			this._designation = obj.getDesignation();
			this._facebookUrl = obj.getFacebookUrl();
			this._twitterUrl = obj.getTwitterUrl();
			this._linkedInUrl = obj.getLinkedInUrl();
		}
	}

	private String lastName;
	private String country;
	private String officeName;
	private String userImageUrl;
	private String city;
	private String postalCode;
	private String twitterUrl;
	private String phone2;
	private String phone3;
	private String source;
	private String agentProfilePage;
	private String title;
	private String phone1;
	private String phone3Type;
	private String facebookUrl;
	private String middleInitial;
	private String localCountry;
	private String officeId;
	private String street1;
	private String street2;
	private String state;
	private String email;
	private String phone2Type;
	private String[] metaOrgKeys;
	private String linkedInUrl;
	private String timeZoneId;
	private String officeEmail;
	private String phone1Type;
	private String firstName;
	private String license;
	private String companyId;
	private String externalUserId;
	private com.imprev.jsonrpc.generated.common.NameValue[] meta;
	private String orgLabel;
	private String designation;
	private String localLanguage;
	private String officeUrl;
	private UserStatus status;

	public ExternalUser() {
		super();
	}

	public ExternalUser(java.util.Map _map) throws com.bitmechanic.barrister.RpcException {
		this((String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("externalUserId"), false),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("source"), false),
				(com.imprev.jsonrpc.generated.common.NameValue[]) com.bitmechanic.barrister.ArrayTypeConverter
						.unmarshalList(com.imprev.jsonrpc.generated.common.NameValue.class, _map.get("meta"), false),
				(String[]) com.bitmechanic.barrister.StringTypeConverter.unmarshalList(_map.get("metaOrgKeys"), false),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("orgLabel"), true),
				(UserStatus) UserStatus.unmarshal(_map.get("status"), false),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("localLanguage"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("localCountry"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("email"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("firstName"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("middleInitial"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("lastName"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("street1"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("street2"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("city"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("state"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("country"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("postalCode"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("userImageUrl"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("companyId"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("officeId"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("officeName"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("officeUrl"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("officeEmail"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("agentProfilePage"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("phone1"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("phone1Type"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("phone2"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("phone2Type"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("phone3"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("phone3Type"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("timeZoneId"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("title"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("license"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("designation"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("facebookUrl"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("twitterUrl"), true),
				(String) com.bitmechanic.barrister.StringTypeConverter.unmarshal(_map.get("linkedInUrl"), true));
	}

	@org.codehaus.jackson.annotate.JsonCreator
	public ExternalUser(@org.codehaus.jackson.annotate.JsonProperty("externalUserId") String externalUserId,
			@org.codehaus.jackson.annotate.JsonProperty("source") String source,
			@org.codehaus.jackson.annotate.JsonProperty("meta") com.imprev.jsonrpc.generated.common.NameValue[] meta,
			@org.codehaus.jackson.annotate.JsonProperty("metaOrgKeys") String[] metaOrgKeys,
			@org.codehaus.jackson.annotate.JsonProperty("orgLabel") String orgLabel,
			@org.codehaus.jackson.annotate.JsonProperty("status") UserStatus status,
			@org.codehaus.jackson.annotate.JsonProperty("localLanguage") String localLanguage,
			@org.codehaus.jackson.annotate.JsonProperty("localCountry") String localCountry,
			@org.codehaus.jackson.annotate.JsonProperty("email") String email,
			@org.codehaus.jackson.annotate.JsonProperty("firstName") String firstName,
			@org.codehaus.jackson.annotate.JsonProperty("middleInitial") String middleInitial,
			@org.codehaus.jackson.annotate.JsonProperty("lastName") String lastName,
			@org.codehaus.jackson.annotate.JsonProperty("street1") String street1,
			@org.codehaus.jackson.annotate.JsonProperty("street2") String street2,
			@org.codehaus.jackson.annotate.JsonProperty("city") String city,
			@org.codehaus.jackson.annotate.JsonProperty("state") String state,
			@org.codehaus.jackson.annotate.JsonProperty("country") String country,
			@org.codehaus.jackson.annotate.JsonProperty("postalCode") String postalCode,
			@org.codehaus.jackson.annotate.JsonProperty("userImageUrl") String userImageUrl,
			@org.codehaus.jackson.annotate.JsonProperty("companyId") String companyId,
			@org.codehaus.jackson.annotate.JsonProperty("officeId") String officeId,
			@org.codehaus.jackson.annotate.JsonProperty("officeName") String officeName,
			@org.codehaus.jackson.annotate.JsonProperty("officeUrl") String officeUrl,
			@org.codehaus.jackson.annotate.JsonProperty("officeEmail") String officeEmail,
			@org.codehaus.jackson.annotate.JsonProperty("agentProfilePage") String agentProfilePage,
			@org.codehaus.jackson.annotate.JsonProperty("phone1") String phone1,
			@org.codehaus.jackson.annotate.JsonProperty("phone1Type") String phone1Type,
			@org.codehaus.jackson.annotate.JsonProperty("phone2") String phone2,
			@org.codehaus.jackson.annotate.JsonProperty("phone2Type") String phone2Type,
			@org.codehaus.jackson.annotate.JsonProperty("phone3") String phone3,
			@org.codehaus.jackson.annotate.JsonProperty("phone3Type") String phone3Type,
			@org.codehaus.jackson.annotate.JsonProperty("timeZoneId") String timeZoneId,
			@org.codehaus.jackson.annotate.JsonProperty("title") String title,
			@org.codehaus.jackson.annotate.JsonProperty("license") String license,
			@org.codehaus.jackson.annotate.JsonProperty("designation") String designation,
			@org.codehaus.jackson.annotate.JsonProperty("facebookUrl") String facebookUrl,
			@org.codehaus.jackson.annotate.JsonProperty("twitterUrl") String twitterUrl,
			@org.codehaus.jackson.annotate.JsonProperty("linkedInUrl") String linkedInUrl) {
		super();
		this.externalUserId = externalUserId;
		this.source = source;
		this.meta = meta;
		this.metaOrgKeys = metaOrgKeys;
		this.orgLabel = orgLabel;
		this.status = status;
		this.localLanguage = localLanguage;
		this.localCountry = localCountry;
		this.email = email;
		this.firstName = firstName;
		this.middleInitial = middleInitial;
		this.lastName = lastName;
		this.street1 = street1;
		this.street2 = street2;
		this.city = city;
		this.state = state;
		this.country = country;
		this.postalCode = postalCode;
		this.userImageUrl = userImageUrl;
		this.companyId = companyId;
		this.officeId = officeId;
		this.officeName = officeName;
		this.officeUrl = officeUrl;
		this.officeEmail = officeEmail;
		this.agentProfilePage = agentProfilePage;
		this.phone1 = phone1;
		this.phone1Type = phone1Type;
		this.phone2 = phone2;
		this.phone2Type = phone2Type;
		this.phone3 = phone3;
		this.phone3Type = phone3Type;
		this.timeZoneId = timeZoneId;
		this.title = title;
		this.license = license;
		this.designation = designation;
		this.facebookUrl = facebookUrl;
		this.twitterUrl = twitterUrl;
		this.linkedInUrl = linkedInUrl;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCountry() {
		return this.country;
	}

	public void setOfficeName(String officeName) {
		this.officeName = officeName;
	}

	public String getOfficeName() {
		return this.officeName;
	}

	public void setUserImageUrl(String userImageUrl) {
		this.userImageUrl = userImageUrl;
	}

	public String getUserImageUrl() {
		return this.userImageUrl;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCity() {
		return this.city;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public String getPostalCode() {
		return this.postalCode;
	}

	public void setTwitterUrl(String twitterUrl) {
		this.twitterUrl = twitterUrl;
	}

	public String getTwitterUrl() {
		return this.twitterUrl;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone3(String phone3) {
		this.phone3 = phone3;
	}

	public String getPhone3() {
		return this.phone3;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getSource() {
		return this.source;
	}

	public void setAgentProfilePage(String agentProfilePage) {
		this.agentProfilePage = agentProfilePage;
	}

	public String getAgentProfilePage() {
		return this.agentProfilePage;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getTitle() {
		return this.title;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone3Type(String phone3Type) {
		this.phone3Type = phone3Type;
	}

	public String getPhone3Type() {
		return this.phone3Type;
	}

	public void setFacebookUrl(String facebookUrl) {
		this.facebookUrl = facebookUrl;
	}

	public String getFacebookUrl() {
		return this.facebookUrl;
	}

	public void setMiddleInitial(String middleInitial) {
		this.middleInitial = middleInitial;
	}

	public String getMiddleInitial() {
		return this.middleInitial;
	}

	public void setLocalCountry(String localCountry) {
		this.localCountry = localCountry;
	}

	public String getLocalCountry() {
		return this.localCountry;
	}

	public void setOfficeId(String officeId) {
		this.officeId = officeId;
	}

	public String getOfficeId() {
		return this.officeId;
	}

	public void setStreet1(String street1) {
		this.street1 = street1;
	}

	public String getStreet1() {
		return this.street1;
	}

	public void setStreet2(String street2) {
		this.street2 = street2;
	}

	public String getStreet2() {
		return this.street2;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getState() {
		return this.state;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getEmail() {
		return this.email;
	}

	public void setPhone2Type(String phone2Type) {
		this.phone2Type = phone2Type;
	}

	public String getPhone2Type() {
		return this.phone2Type;
	}

	public void setMetaOrgKeys(String[] metaOrgKeys) {
		this.metaOrgKeys = metaOrgKeys;
	}

	public String[] getMetaOrgKeys() {
		return this.metaOrgKeys;
	}

	public void setLinkedInUrl(String linkedInUrl) {
		this.linkedInUrl = linkedInUrl;
	}

	public String getLinkedInUrl() {
		return this.linkedInUrl;
	}

	public void setTimeZoneId(String timeZoneId) {
		this.timeZoneId = timeZoneId;
	}

	public String getTimeZoneId() {
		return this.timeZoneId;
	}

	public void setOfficeEmail(String officeEmail) {
		this.officeEmail = officeEmail;
	}

	public String getOfficeEmail() {
		return this.officeEmail;
	}

	public void setPhone1Type(String phone1Type) {
		this.phone1Type = phone1Type;
	}

	public String getPhone1Type() {
		return this.phone1Type;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setLicense(String license) {
		this.license = license;
	}

	public String getLicense() {
		return this.license;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	public String getCompanyId() {
		return this.companyId;
	}

	public void setExternalUserId(String externalUserId) {
		this.externalUserId = externalUserId;
	}

	public String getExternalUserId() {
		return this.externalUserId;
	}

	public void setMeta(com.imprev.jsonrpc.generated.common.NameValue[] meta) {
		this.meta = meta;
	}

	public com.imprev.jsonrpc.generated.common.NameValue[] getMeta() {
		return this.meta;
	}

	public void setOrgLabel(String orgLabel) {
		this.orgLabel = orgLabel;
	}

	public String getOrgLabel() {
		return this.orgLabel;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setLocalLanguage(String localLanguage) {
		this.localLanguage = localLanguage;
	}

	public String getLocalLanguage() {
		return this.localLanguage;
	}

	public void setOfficeUrl(String officeUrl) {
		this.officeUrl = officeUrl;
	}

	public String getOfficeUrl() {
		return this.officeUrl;
	}

	public void setStatus(UserStatus status) {
		this.status = status;
	}

	public UserStatus getStatus() {
		return this.status;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("ExternalUser:");
		sb.append(" lastName=").append(lastName);
		sb.append(" country=").append(country);
		sb.append(" officeName=").append(officeName);
		sb.append(" userImageUrl=").append(userImageUrl);
		sb.append(" city=").append(city);
		sb.append(" postalCode=").append(postalCode);
		sb.append(" twitterUrl=").append(twitterUrl);
		sb.append(" phone2=").append(phone2);
		sb.append(" phone3=").append(phone3);
		sb.append(" source=").append(source);
		sb.append(" agentProfilePage=").append(agentProfilePage);
		sb.append(" title=").append(title);
		sb.append(" phone1=").append(phone1);
		sb.append(" phone3Type=").append(phone3Type);
		sb.append(" facebookUrl=").append(facebookUrl);
		sb.append(" middleInitial=").append(middleInitial);
		sb.append(" localCountry=").append(localCountry);
		sb.append(" officeId=").append(officeId);
		sb.append(" street1=").append(street1);
		sb.append(" street2=").append(street2);
		sb.append(" state=").append(state);
		sb.append(" email=").append(email);
		sb.append(" phone2Type=").append(phone2Type);
		sb.append(" metaOrgKeys=").append(java.util.Arrays.toString(metaOrgKeys));
		sb.append(" linkedInUrl=").append(linkedInUrl);
		sb.append(" timeZoneId=").append(timeZoneId);
		sb.append(" officeEmail=").append(officeEmail);
		sb.append(" phone1Type=").append(phone1Type);
		sb.append(" firstName=").append(firstName);
		sb.append(" license=").append(license);
		sb.append(" companyId=").append(companyId);
		sb.append(" externalUserId=").append(externalUserId);
		sb.append(" meta=").append(java.util.Arrays.toString(meta));
		sb.append(" orgLabel=").append(orgLabel);
		sb.append(" designation=").append(designation);
		sb.append(" localLanguage=").append(localLanguage);
		sb.append(" officeUrl=").append(officeUrl);
		sb.append(" status=").append(status);
		return sb.toString();
	}

	@Override
	public boolean equals(Object _other) {
		if (this == _other) {
			return true;
		}
		if (_other == null) {
			return false;
		}
		if (!(_other instanceof ExternalUser)) {
			return false;
		}
		ExternalUser _o = (ExternalUser) _other;
		if (lastName == null && _o.lastName != null) {
			return false;
		} else if (lastName != null && !lastName.equals(_o.lastName)) {
			return false;
		}
		if (country == null && _o.country != null) {
			return false;
		} else if (country != null && !country.equals(_o.country)) {
			return false;
		}
		if (officeName == null && _o.officeName != null) {
			return false;
		} else if (officeName != null && !officeName.equals(_o.officeName)) {
			return false;
		}
		if (userImageUrl == null && _o.userImageUrl != null) {
			return false;
		} else if (userImageUrl != null && !userImageUrl.equals(_o.userImageUrl)) {
			return false;
		}
		if (city == null && _o.city != null) {
			return false;
		} else if (city != null && !city.equals(_o.city)) {
			return false;
		}
		if (postalCode == null && _o.postalCode != null) {
			return false;
		} else if (postalCode != null && !postalCode.equals(_o.postalCode)) {
			return false;
		}
		if (twitterUrl == null && _o.twitterUrl != null) {
			return false;
		} else if (twitterUrl != null && !twitterUrl.equals(_o.twitterUrl)) {
			return false;
		}
		if (phone2 == null && _o.phone2 != null) {
			return false;
		} else if (phone2 != null && !phone2.equals(_o.phone2)) {
			return false;
		}
		if (phone3 == null && _o.phone3 != null) {
			return false;
		} else if (phone3 != null && !phone3.equals(_o.phone3)) {
			return false;
		}
		if (source == null && _o.source != null) {
			return false;
		} else if (source != null && !source.equals(_o.source)) {
			return false;
		}
		if (agentProfilePage == null && _o.agentProfilePage != null) {
			return false;
		} else if (agentProfilePage != null && !agentProfilePage.equals(_o.agentProfilePage)) {
			return false;
		}
		if (title == null && _o.title != null) {
			return false;
		} else if (title != null && !title.equals(_o.title)) {
			return false;
		}
		if (phone1 == null && _o.phone1 != null) {
			return false;
		} else if (phone1 != null && !phone1.equals(_o.phone1)) {
			return false;
		}
		if (phone3Type == null && _o.phone3Type != null) {
			return false;
		} else if (phone3Type != null && !phone3Type.equals(_o.phone3Type)) {
			return false;
		}
		if (facebookUrl == null && _o.facebookUrl != null) {
			return false;
		} else if (facebookUrl != null && !facebookUrl.equals(_o.facebookUrl)) {
			return false;
		}
		if (middleInitial == null && _o.middleInitial != null) {
			return false;
		} else if (middleInitial != null && !middleInitial.equals(_o.middleInitial)) {
			return false;
		}
		if (localCountry == null && _o.localCountry != null) {
			return false;
		} else if (localCountry != null && !localCountry.equals(_o.localCountry)) {
			return false;
		}
		if (officeId == null && _o.officeId != null) {
			return false;
		} else if (officeId != null && !officeId.equals(_o.officeId)) {
			return false;
		}
		if (street1 == null && _o.street1 != null) {
			return false;
		} else if (street1 != null && !street1.equals(_o.street1)) {
			return false;
		}
		if (street2 == null && _o.street2 != null) {
			return false;
		} else if (street2 != null && !street2.equals(_o.street2)) {
			return false;
		}
		if (state == null && _o.state != null) {
			return false;
		} else if (state != null && !state.equals(_o.state)) {
			return false;
		}
		if (email == null && _o.email != null) {
			return false;
		} else if (email != null && !email.equals(_o.email)) {
			return false;
		}
		if (phone2Type == null && _o.phone2Type != null) {
			return false;
		} else if (phone2Type != null && !phone2Type.equals(_o.phone2Type)) {
			return false;
		}
		if (metaOrgKeys == null && _o.metaOrgKeys != null) {
			return false;
		} else if (metaOrgKeys != null && !java.util.Arrays.equals(metaOrgKeys, _o.metaOrgKeys)) {
			return false;
		}
		if (linkedInUrl == null && _o.linkedInUrl != null) {
			return false;
		} else if (linkedInUrl != null && !linkedInUrl.equals(_o.linkedInUrl)) {
			return false;
		}
		if (timeZoneId == null && _o.timeZoneId != null) {
			return false;
		} else if (timeZoneId != null && !timeZoneId.equals(_o.timeZoneId)) {
			return false;
		}
		if (officeEmail == null && _o.officeEmail != null) {
			return false;
		} else if (officeEmail != null && !officeEmail.equals(_o.officeEmail)) {
			return false;
		}
		if (phone1Type == null && _o.phone1Type != null) {
			return false;
		} else if (phone1Type != null && !phone1Type.equals(_o.phone1Type)) {
			return false;
		}
		if (firstName == null && _o.firstName != null) {
			return false;
		} else if (firstName != null && !firstName.equals(_o.firstName)) {
			return false;
		}
		if (license == null && _o.license != null) {
			return false;
		} else if (license != null && !license.equals(_o.license)) {
			return false;
		}
		if (companyId == null && _o.companyId != null) {
			return false;
		} else if (companyId != null && !companyId.equals(_o.companyId)) {
			return false;
		}
		if (externalUserId == null && _o.externalUserId != null) {
			return false;
		} else if (externalUserId != null && !externalUserId.equals(_o.externalUserId)) {
			return false;
		}
		if (meta == null && _o.meta != null) {
			return false;
		} else if (meta != null && !java.util.Arrays.equals(meta, _o.meta)) {
			return false;
		}
		if (orgLabel == null && _o.orgLabel != null) {
			return false;
		} else if (orgLabel != null && !orgLabel.equals(_o.orgLabel)) {
			return false;
		}
		if (designation == null && _o.designation != null) {
			return false;
		} else if (designation != null && !designation.equals(_o.designation)) {
			return false;
		}
		if (localLanguage == null && _o.localLanguage != null) {
			return false;
		} else if (localLanguage != null && !localLanguage.equals(_o.localLanguage)) {
			return false;
		}
		if (officeUrl == null && _o.officeUrl != null) {
			return false;
		} else if (officeUrl != null && !officeUrl.equals(_o.officeUrl)) {
			return false;
		}
		if (status == null && _o.status != null) {
			return false;
		} else if (status != null && !status.equals(_o.status)) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		int _hash = 1;
		_hash = _hash * 31 + (lastName == null ? 0 : lastName.hashCode());
		_hash = _hash * 31 + (country == null ? 0 : country.hashCode());
		_hash = _hash * 31 + (officeName == null ? 0 : officeName.hashCode());
		_hash = _hash * 31 + (userImageUrl == null ? 0 : userImageUrl.hashCode());
		_hash = _hash * 31 + (city == null ? 0 : city.hashCode());
		_hash = _hash * 31 + (postalCode == null ? 0 : postalCode.hashCode());
		_hash = _hash * 31 + (twitterUrl == null ? 0 : twitterUrl.hashCode());
		_hash = _hash * 31 + (phone2 == null ? 0 : phone2.hashCode());
		_hash = _hash * 31 + (phone3 == null ? 0 : phone3.hashCode());
		_hash = _hash * 31 + (source == null ? 0 : source.hashCode());
		_hash = _hash * 31 + (agentProfilePage == null ? 0 : agentProfilePage.hashCode());
		_hash = _hash * 31 + (title == null ? 0 : title.hashCode());
		_hash = _hash * 31 + (phone1 == null ? 0 : phone1.hashCode());
		_hash = _hash * 31 + (phone3Type == null ? 0 : phone3Type.hashCode());
		_hash = _hash * 31 + (facebookUrl == null ? 0 : facebookUrl.hashCode());
		_hash = _hash * 31 + (middleInitial == null ? 0 : middleInitial.hashCode());
		_hash = _hash * 31 + (localCountry == null ? 0 : localCountry.hashCode());
		_hash = _hash * 31 + (officeId == null ? 0 : officeId.hashCode());
		_hash = _hash * 31 + (street1 == null ? 0 : street1.hashCode());
		_hash = _hash * 31 + (street2 == null ? 0 : street2.hashCode());
		_hash = _hash * 31 + (state == null ? 0 : state.hashCode());
		_hash = _hash * 31 + (email == null ? 0 : email.hashCode());
		_hash = _hash * 31 + (phone2Type == null ? 0 : phone2Type.hashCode());
		_hash = _hash * 31 + (metaOrgKeys == null ? 0 : java.util.Arrays.hashCode(metaOrgKeys));
		_hash = _hash * 31 + (linkedInUrl == null ? 0 : linkedInUrl.hashCode());
		_hash = _hash * 31 + (timeZoneId == null ? 0 : timeZoneId.hashCode());
		_hash = _hash * 31 + (officeEmail == null ? 0 : officeEmail.hashCode());
		_hash = _hash * 31 + (phone1Type == null ? 0 : phone1Type.hashCode());
		_hash = _hash * 31 + (firstName == null ? 0 : firstName.hashCode());
		_hash = _hash * 31 + (license == null ? 0 : license.hashCode());
		_hash = _hash * 31 + (companyId == null ? 0 : companyId.hashCode());
		_hash = _hash * 31 + (externalUserId == null ? 0 : externalUserId.hashCode());
		_hash = _hash * 31 + (meta == null ? 0 : java.util.Arrays.hashCode(meta));
		_hash = _hash * 31 + (orgLabel == null ? 0 : orgLabel.hashCode());
		_hash = _hash * 31 + (designation == null ? 0 : designation.hashCode());
		_hash = _hash * 31 + (localLanguage == null ? 0 : localLanguage.hashCode());
		_hash = _hash * 31 + (officeUrl == null ? 0 : officeUrl.hashCode());
		_hash = _hash * 31 + (status == null ? 0 : status.hashCode());
		return _hash;
	}
}
