yodataIoApi:
  schemaPath: amplify/backend/api/yodataIoApi/schema.json
  includes:
    - '*schema.json'
  excludes:
    - amplify/**
  extensions:
    amplify:
      graphQLApiId: of6mmjl6ijf7lfnaipzont6qcy
      codeGenTarget: typescript
      generatedFileName: api.ts
yodataApi:
  schemaPath: amplify/backend/api/yodataApi/schema.json
  includes:
    - ./schema.graphql
  excludes:
    - amplify/**
  extensions:
    amplify:
      graphQLApiId: z2l74eszv5d3fkcchyo3qw6eb4
      codeGenTarget: typescript
      generatedFileName: API.ts
    endPoints: >-
      https://5felgrtnarg6nharqckkmrktk4.appsync-api.us-west-2.amazonaws.com/graphql
