// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://5felgrtnarg6nharqckkmrktk4.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-west-2:763a23ef-8a7e-4404-839b-3314b6aa9da2",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_DuBHWmpYM",
    "aws_user_pools_web_client_id": "3k48ru6u1me2gh9k3t1uvod69i"
};


export default awsmobile;
