module.exports = {
  ADDITIONAL_PROPERTIES: "@additionalProperties",
  CONTEXT: "@context",
  DEFAULT: "@default",
  FRAME: "@frame",
  GRAPH: "@graph",
  ID: "id",
  INDEX: "@index",
  KEY_ORDER: "@keyOrder",
  LANGUAGE: "@language",
  LIST: "@list",
  NAME: "name",
  NEST: "container",
  NONE: "@none",
  PREFIX: "@prefix",
  REDACT: "@redact",
  REMOVE: "@remove",
  REVERSE: "@reverse",
  SET: "@set",
  TYPE: "type",
  VALUE: "value",
  VERSION: "@version",
  VOCAB: "@vocab"
};