module.exports = {
	type: 'UpdateAction',
	object: {
		type: 'Contact',
		identifier: ['contactKey',
			{ name: 'BrokerOffice', value: 'originatingSystemContactKey' }],
		honorificPrefix: 'namePrefix',
		givenName: 'firstName',
		additionalName: ['middleName', 'nickname'],
		familyName: 'lastName',
		honorificSuffix: 'nameSuffix',
		name: 'fullName',
		jobTitle: 'jobTitle',
		worksFor: 'company',
		preferredContactMethod: 'preferredContactMethod',
		preferredPhoneType: 'preferredPhoneType',
		preferredTime: 'preferredTime',
		address: [
			{
				type: 'PostalAddress',
				identifier: 'addressKey',
				name: 'addressType',
				streetAddress: 'address1 address2',
				addressLocality: 'city',
				addressRegion: 'stateOrProvince',
				postalCode: 'postalCode',
				addressCountry: 'country',
				dateCreated: '2017-05-24T20:16:12.8419099-05:00',
				dateModified: '2017-05-24T20:16:12.8419099-05:00'
			}
		],
		contactPoint: [{
			type: 'ContactPoint',
			identifier: 'emailAddressKey',
			email: 'emailAddress',
			name: 'emailType',
			usedForApm: true,
			dateCreated: '2017-05-21T14:03:57.8640648-05:00',
			dateModified: '2017-05-21T14:03:57.957819-05:00'
		}],
		comment: [{
			type: 'Comment',
			identifier: 'noteKey',
			author: 'addedByMember',
			value: 'note',
			dateCreated: '2017-05-24T12:09:45'
		}],
		homeLocation: [{
			type: 'ContactPoint',
			identifier: 'homePhoneNumberKey',
			name: 'Home',
			telephone: 'homePhoneNumber',
			dateCreated: '2017-05-21T14:03:57.8640648-05:00',
			dateModified: '2017-05-21T14:03:57.957819-05:00'
		}],
		workLocation: [{
			type: 'ContactPoint',
			identifier: 'workPhoneNumberKey',
			name: 'Work',
			telephone: 'workPhoneNumber',
			dateCreated: '2017-05-21T14:03:57.8640648-05:00',
			dateModified: '2017-05-21T14:03:57.957819-05:00'
		}]
	},
	dateCreated: '2017-05-21T14:03:57.8796905-05:00',
	dateModified: '2017-05-21T14:03:57.8796905-05:00',
	acceptedByMember: true,
	recipient: ['https://ct301.ds.bhhsresource.com/profile/card#me'],
	instrument: [{
		leadSource: 'leadSource',
		subLeadSource: 'subLeadSource',
		originalReferrerUrl: 'originalReferrerUrl',
		isLead: true,
		dateCreated: '2017-05-21T14:03:57.8796905-05:00'
	}],
	includes: [{
		listingKey: 'listingKey',
		listingId: 'listingId',
		listAor: 'listAor',
		mlsStatus: 'mlsStatus',
		listingContractDate: 'listingContractDate',
		daysOnMarket: 1,
		listPrice: 169900,
		streetNumber: 'streetNumber',
		streetNumberNumeric: 1,
		streetDirPrefix: 'streetDirPrefix',
		streetName: 'streetName',
		streetSuffix: 'streetSuffix',
		unitNumber: 'unitNumber',
		city: 'city',
		stateOrProvince: 'stateOrProvince',
		postalCode: 'postalCode',
		country: 'country',
		countyOrParish: 'countyOrParish',
		subdivisionName: 'subdivisionName',
		directions: 'directions',
		listAgentFirstName: 'listAgentFirstName',
		listAgentLastName: 'listAgentLastName',
		listAgentFullName: 'listAgentFullName',
		listAgentEmail: 'listAgentEmail',
		listAgentMlsId: 'listAgentMlsId',
		listOfficeMlsId: 'listOfficeMlsId',
		listingTypeName: 'listingTypeName',
		propertyType: 'propertyType',
		propertySubType: 'propertySubType',
		lotSizeArea: 0.01,
		lotSizeDimensions: 'lotSizeDimensions',
		poolFeatures: 'poolFeatures',
		bathroomsTotal: '3',
		bedroomsTotal: '3',
		garageSpaces: 0,
		stories: 2,
		yearBuilt: 2002,
		heating: 'heating',
		cooling: 'cooling',
		interiorFeatures: 'interiorFeatures',
		exteriorFeatures: 'exteriorFeatures',
		roof: 'roof',
		contactNote: 'contactNote',
		listBrokerName: 'listBrokerName',
		listBrokerPhone: 'listBrokerPhone',
		propertyUrl: 'propertyUrl',
		timestampEntered: '2017-05-21T14:03:57.8796905-05:00',
		timestampModified: '2017-05-21T14:03:57.8796905-05:00'
	}]
}
